### ISSUE TITLE
Polygon NFT doesn't appear on the Lend Dashboard after listed for lending - causing a lot of issues/FUD in Twitter and in the community

### ISSUE THREAD

**Issue by veracomm** [veradefi/vera.financial#35]
Here is the issue for the guy whose polygon NFT didn't show up on his dashboard after lending. He thinks the NFT is stolen by the contract.

Tx id - 0x47e51cc7d3d0435b1e8ba65a1292a42169ae58c5bd31e486afb3ad4225032d21

Note: He also claims that he had a failed lending transaction and 3 days later his NFT automatically went to the contract. Can a transaction be pending for 3 days?? Questionable.

**Comment by veracomm** [comment]
> Talk to a Polygon Dev on the [Live support page](https://forummaticnetwork.org/) so that your issue can be looked into.

@Devjohn12 ???????

**Comment by hardik0207** [comment]
@veracomm issue has been fixed  and NFT is showing for lend, please verify it

**Comment by veracomm** [comment]
> @veracomm issue has been fixed and NFT is showing for lend, please verify it

This issue hasn't fixed at the dashboard. NFT is still not showing up on the dashboard for the user. How can he/she cancel lending?

Can this be fixed ASAP.

![Uploading image.png…]()

**Comment by hardik0207** [comment]
Hey @veracomm 
Please check now

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/10892303/160233490-e83d0277-3250-4569-af49-aec63509ebb6.png">

**Comment by veracomm** [comment]
hey @hardik0207 

I confirmed the user the they can access the NFT on the dashboard now. They have withdrawn the NFT and started using in their game.

However that NFT is still showing up for rent. Weird!

**Comment by Devjohn12** [comment]
Haven’t you talk to their Dev yet about it?

**Comment by veracomm** [comment]
@Devjohn12  are you with vera team? Why would I talk to Polygon devs about an issue specific to vera rental market?

**Comment by hardik0207** [comment]
@veracomm fixed issues, please check and let me know

**Comment by veracomm** [comment]
@hardik0207 NFT is not longer for rent, thank you!

Closing this issue.
